services:
  - type: web
    name: soundcloud-bot # Или ваше имя
    env: docker
    plan: free
    envVars: # Место для ваших секретов. Введите их на сайте.
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: STORAGE_CHANNEL_ID
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: soundcloud-bot
          property: url